apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-despachos
  namespace: innovatech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-despachos
  template:
    metadata:
      labels:
        app: mysql-despachos
    spec:
      containers:
        - name: mysql-despachos
          image: mysql:8.4
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-despachos-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-despachos-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-despachos-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-despachos-secret
                  key: MYSQL_ROOT_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"