apiVersion: v1
kind: Secret
metadata:
  name: mysql-despachos-secret
  namespace: innovatech
type: Opaque
stringData:
  MYSQL_DATABASE: despachosdb
  MYSQL_USER: despachosuser
  MYSQL_PASSWORD: despachospass
  MYSQL_ROOT_PASSWORD: rootpass